### ISSUE TITLE
Breadcrumb className requires !important

### ISSUE THREAD

**Issue by adamdonahue** [Semantic-Org/Semantic-UI-React#1630]
I have:

```jsx
<Breadcrumb className="Toolbar__breadcrumb">
  <Breadcrumb.Section>...</Breadcrumb.Section>
</Breadcrumb>
```

and

```scss
.Toolbar__breadcrumb {
  margin-top: 15px;
}
```

But `margin-top` is ignored unless I use `!important`.  

What would be the proper way to override at this level using a BEM approach?
