### ISSUE TITLE
Toggle checkbox color [feature request]

### ISSUE THREAD

**Issue by kirillku** [Semantic-Org/Semantic-UI-React#1850]
Is it possible to add color prop to `<Checkbox toggle />`? 
Right now it's with `!important` and it's not even possible to change color without changing `semantic.css`.
```css
.ui.toggle.checkbox input:checked~.box:before,
.ui.toggle.checkbox input:checked~label:before {
  background-color: #2185D0 !important
}
.ui.toggle.checkbox input:focus:checked~.box:before,
.ui.toggle.checkbox input:focus:checked~label:before {
  background-color: #0d71bb !important
}
```

**Comment by layershifter** [comment]
If it will be done in SUI, we will impliment it. SUIR doesn't deal with CSS at all, it only generates the valid markup.

**Comment by farhansalam** [comment]
this works in SUIR

```CSS
.ui.toggle.checkbox input:focus:checked~.box:before,
.ui.toggle.checkbox input:focus:checked~label:before {
    background-color: teal !important
}

.ui.toggle.checkbox .box:before, .ui.toggle.checkbox label:before {
    background-color: grey;
}

```
