### ISSUE TITLE
Add offset to Columns

### ISSUE THREAD

**Issue by eanplatter** [Semantic-Org/Semantic-UI-React#26]
`<Column width={4} offset={2} />`

**Comment by kyleturco** [comment]
Is this still relevant? If so, is this for Radiant or Stardust itself? I'm not sure Stardust has column offset specified

**Comment by levithomason** [comment]
Wow, actually, Semantic UI plain does not support offsets.  This is really surprising.  Suppose we'll stick to using an empty column.

Per Jack himself:

---

**https://github.com/Semantic-Org/Semantic-UI/issues/863** "[Grid] Add Grid Offsets"
![image](https://cloud.githubusercontent.com/assets/5067638/11313337/0491a652-8f91-11e5-8a85-d4468feed945.png)

---

**https://groups.google.com/forum/#!msg/semantic-ui/PQNbllIob5o/DENWCyfCqlIJ**
![image](https://cloud.githubusercontent.com/assets/5067638/11313317/d6fe78fa-8f90-11e5-90a2-8b2a1edcf879.png)

**Comment by kyleturco** [comment]
Well, that's that I suppose

**Comment by levithomason** [comment]
Someone mentioned on that google group an override style that allowed offsets of some sort, but I do not see how this achieves anything like the bootstrap offsets:

``` less
<div class="one wide column offset"></div>

@media only screen and (max-width: 767px) {
 .ui.stackable.grid > .column.offset, .ui.stackable.grid > .row > .column.offset{
    display:none !important;
  }
}
```
