### ISSUE TITLE
Loader is not visible in a Modal

### ISSUE THREAD

**Issue by james-ff** [Semantic-Org/Semantic-UI-React#3133]
### Steps
Place a Loader component in a Modal Content component

### Expected Result
Spinning Loading Icon.

### Actual Result
Icon not visible

### Version
0.82.2

### Testcase

Taken from the Modal Example:
```
import React from 'react'
import { Button, Header, Image, Loader, Modal } from 'semantic-ui-react'

const ModalModalExample = () => (
  <Modal trigger={<Button>Show Modal</Button>}>
    <Modal.Header>Select a Photo</Modal.Header>
    <Modal.Content image>
      <Image wrapped size='medium' src='https://react.semantic-ui.com/images/avatar/large/rachel.png' />
      <Modal.Description>
        <Header>Default Profile Image</Header>
        <p>We've found the following gravatar image associated with your e-mail address.</p>
        <p>Is it okay to use this photo?</p>
        <Loader active inline='centered' />
      </Modal.Description>
    </Modal.Content>
  </Modal>
)

export default ModalModalExample
```

**Comment by layershifter** [comment]
It's a known CSS issue: https://github.com/Semantic-Org/Semantic-UI/issues/4014

There is also a workaround: 

```css
.ui.dimmer .ui.workaround.loader:before {
  border-color: rgba(0,0,0,.1);
}
          
.ui.dimmer .ui.workaround.loader:after {
  border-color: #767676 transparent transparent;
}
```

```jsx
<Loader active className='workaround' size='large' inline='centered' />
```

**Comment by james-ff** [comment]
Thank you for the workaround! @layershifter

**Comment by JohnLemberger** [comment]
![image](https://user-images.githubusercontent.com/1387458/55583195-e7076880-56e6-11e9-9875-09ec75ffa8ea.png)

**Comment by mac-s-g** [comment]
for those using Styled Components:
```
const Loading = Styled(Loader)`
  &&&& {
    &:after {
      border-color: #767676 #ddd #ddd;
    }
  }
`
```

looks great in a Modal!

**Comment by ireznik** [comment]
Do I understand it correctly that all issues concerning this behaviour were resolved or closed but the fix is to be done by hand if I want to display a loader in modals?

**Comment by samuel-knutson** [comment]
If you want to apply @layershifter's workaround to all modals without the extra css class:

```css
.ui.dimmer .ui.modal .ui.loader:before {
  border-color: rgba(0,0,0,.1);
}
          
.ui.dimmer .ui.modal .ui.loader:after {
  border-color: #767676 transparent transparent;
}
```
