### ISSUE TITLE
Better clearfix

### ISSUE THREAD

**Issue by henck** [Semantic-Org/Semantic-UI-React#3347]
### Problem description
When you use the `Segment` component with floating content in it, then you can add the `clearing` attribute to make it self-clearing. However, this does not work when the `Segment` is also `stacked` or `piled`. The reason appears to be that the clearfix uses the `:after` pseudo-element, and stacked/piled segments make use of it as well.

It should be possible to have stacked/piled Segments that are self-clearing. Maybe Segments should be self-clearing by default, but I may be missing a use-case here.

### Proposed solution

I think the problem could be avoided entirely by sticking an extra `<br style="clear:both"/>` at the bottom of the `Segment`, but that extra element is not very elegant. Perhaps stacked/piled can be rewritten to use only `:before`, reserving `:after` for the clearfix. 

Also, the clearfix currently in use is:

```css
&:after {
  content: ".";
  display: block;
  height: 0;
  clear: both;
  visibility: hidden;
}
```

However, this should be sufficient:

```css
&:after {
  content: "";
  display: table;
  clear: both;
}
```
