### ISSUE TITLE
[Dropdown]Number of item to show with scrolling

### ISSUE THREAD

**Issue by LordOfRhun** [Semantic-Org/Semantic-UI-React#3742]
### Problem description
Even with the "scrolling" parameter, the dropdown component show too many items

### Proposed solution
create a new parameter that takes the number of item its shows with scrolling option

**Comment by layershifter** [comment]
This can be done and should be done with CSS:

```css
.ui.scrolling.dropdown .menu,
.ui.dropdown .scrolling.menu {
  max-height: 200px !important;
}
```
https://codesandbox.io/s/semantic-ui-example-e3y3t
***
However, I recommend to use theming capabilities and override matching variables instead:
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.less#L1128
