### ISSUE TITLE
Placeholder background is always white.

### ISSUE THREAD

**Issue by tresdev** [Semantic-Org/Semantic-UI-React#3769]
## Feature Request
Placeholder component's background should be transparent. Why is it explicitly set to be white?

### Problem description
It's unable to apply when there's background color other than white, because the white background is breaking the design. I think the background color of placeholder should be transparent, not white.

### Proposed solution
Some changes in the placeholder.less file would probably solve the problems.

### MVP
Not yet.

**Comment by layershifter** [comment]
Thank you for creating issue 👍 

#### Short answer:
I don't why it's `white`.

#### Long answer
We don't handle CSS issues there as we maintain only React components. CSS issues should be reported to the main repo: https://github.com/Semantic-Org/Semantic-UI.

However, you have more chances to them fixed now at FUI: https://github.com/fomantic/Fomantic-UI.

#### Workaround
As it's only CSS issue, it can be easily overridden:
```css
.ui.placeholder, .ui.placeholder .image.header:after, .ui.placeholder .line, .ui.placeholder .line:after, .ui.placeholder>:before {
  background-color: red;
}
```
