### ISSUE TITLE
CSS import breaks webpack 5 compilation

### ISSUE THREAD

**Issue by vincentferniotoclock** [Semantic-Org/Semantic-UI-React#4287]
## Bug Report
With Webpack 5 and css-loader 6, the CSS imports breaks the compilation.

### Steps
Starts a new react app with webpack 5 and css-loader v6. Imports Semantic UI css in root component and it should stops working.

### Expected Result
CSS should import correctly and app running as expected

### Actual Result
An error occurs in
```sh
TypeError: Cannot read property 'get' of undefined
during rendering of asset asset/inline|data:application/x-font-ttf;charset=utf-8;;base64,AAEAAAAOAIAAAwBgT1Mv...
```

### Version
2.0.4

### Fix
The main reason for this is an extra ";"  at line 19990 of `semantic.css`
If removed, everything goes fine.
```css
@font-face {
  font-family: 'Step';
  src: url(data:application/x-font-ttf;charset=utf-8;;base64,AAEAAAAOAIAAAw... // this line
}
```
