### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by iansoper** [Semantic-Org/Semantic-UI-React#931]
Is there a good method to add custom icons? I know I could use Icon.less overrides, but I would like to use them with the `Icon` component. It looks like the icon references are from a static list in the [`SUI.js`](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/SUI.js) file. Is there a way to import a different list of icons from a different icon font?

**Comment by levithomason** [comment]
These two are actually equivalent:

```jsx
<Icon name='user' />
<i class="user icon"></i>
```

The component renders down to the HTML, so at the end of the day _elements_ in a Semantic-UI-React app are just plain HTML and CSS.

As you've noted, CSS would be the only way to change the icons.  You would load your own font face and override the class names to use your new icons.

If you're asking, "How can I add new icon names to the list of validated icon names?" then the answer is, you cannot.  The list is fixed from the supported list of core SUI icon names.

LMK if you have any further issues.

**Comment by nolandg** [comment]
See #955 on how to use custom icon names without warnings, namely like so:
````jsx
<Icon className="my-custom-icon-name" />
<Button icon={{ className: 'my-custom-icon-name' }} />
````
In response to OP, you can use any icon font you want or easily build a custom icon font with [Fontello](http://fontello.com/) and then either edit the icon names in that tool to match SUI or just use custom names via `className` prop as above.  You just need some extra stuff in your css to specify the font name and icons, usually this is provided by the font you use or Fontello:
````css
i.icon{
  font-family: fontello;
}
i.icon.custom-icon-name:before { content: '\e800'; } 
````

For extra performance, you can even embed the whole thing in your initial HTML response if you only use a handful of icons:
````css
@font-face {
  font-family: 'fontello';
  src: url('data:application/octet-stream;base64,d0........RgABA') format('woff'),
}
````
